package com.kickdrum.smarthome.util;

public enum ErrorCode {

    AUTH_FAILED,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,

    HOUSE_NOT_FOUND,
    HOUSE_ACCESS_DENIED,
    HOUSE_ALREADY_EXISTS,
    ROOM_ALREADY_EXISTS,
    ROOM_NOT_FOUND,
    ROOM_ACCESS_DENIED,

    DEVICE_NOT_FOUND,
    DEVICE_ALREADY_REGISTERED,
    DEVICE_INVALID_CREDENTIALS,

    INTERNAL_ERROR
}
